version: 2

builds:
  - main: ./cmd/gjq
    binary: gjq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: 0xkowalskidev
    name: gjq
